### PR TITLE
fix: can to build 1.21.4-fabric

### PR DESCRIPTION
**Pull request by ysknkd**
## Description

Thanks to this mod, my son can play the Java version of Minecraft, and it has been incredibly helpful. Thank you so much!

I tried fixing it so it can be built with version 1.21.4. I've never made a mod before, so my method of fixing it might be incorrect, but for now, it seems to be working.

### CODE REVIEW

**Comment by LydiaLambda** [comment]
@isXander @dwaycik https://github.com/isXander/Controlify/issues/471#issue-2721347250

**Comment by dwaycik** [comment]
Nifty :) Now I need to figure out how to install it L

**Review by doublestufed — APPROVED** [review]

**Comment by TaYaKi71751** [comment]
Left Stick with Moving is not working

**Comment by ysknkd** [comment]
Thank you for checking. It worked on Ubuntu, but upon checking just now, it seems that the left stick and some buttons are not working on macOS. The same might apply to Windows as well.

**Comment by ysknkd** [comment]
Apologies, I mistakenly made unnecessary changes, which caused DualInput to stop functioning correctly. I have fixed it.
https://github.com/isXander/Controlify/compare/c7a13b94302aeae4f3147a68efd4d12fc55e5a7a..6781c1f2014604e9373bd6762f44d5231dced18d

**Comment by TaYaKi71751** [comment]
This time, it works properly : )

**Comment by LydiaLambda** [comment]
Working binary :) [LydiaLambda/Controlify/releases](https://github.com/LydiaLambda/Controlify/releases/tag/2.0.0-beta.21)

**Pull request merged**
